version: '3'
services:
  mongodb-nttdynsql:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGOUSER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGOPASSWORD}
    #command: mongod --bind_ip 127.0.0.1
    command: ["--bind_ip_all"]
  nttdynsql:
    image: nttdynsql
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - SECRET=${SECRET}
      - DTURL=${DTURL}
      - DTAPITOKEN=${DTAPITOKEN}
      - PORT=${PORT}
      - MSSQL=${MSSQL}
      - POSTGRES=${POSTGRES}
      - MYSQL=${MYSQL}
      - ORACLE=${ORACLE}
      - MONGOHOST=mongodb-nttdynsql:27017
      - MONGOUSER=${MONGOUSER}
      - MONGOPASSWORD=${MONGOPASSWORD}
      - MONGOAUTHSOURCE=${MONGOAUTHSOURCE}
      - MONGODATABASE=${MONGODATABASE}
      - APSCHEDULERCOLLECTION=${APSCHEDULERCOLLECTION}  
    depends_on:
      - mongodb-nttdynsql    
